print ("=====================================================")
print ("Program Konversi Bilangan Desimal, biner, hexadecimal")
print ("=====================================================")
print ("  ____  __  _  ____  ____    ____  ____   ____ 		 ")
print (" /    ||  |/ ]|    ||    \  /    ||    \ |    |		 ")
print ("|  o  ||  ' /  |  | |  _  ||  o  ||  D  ) |  |		 ") 
print ("|     ||    \  |  | |  |  ||     ||    /  |  | 		 ")
print ("|  _  ||     | |  | |  |  ||  _  ||    \  |  | 		 ")
print ("|  |  ||  .  | |  | |  |  ||  |  ||  .  \ |  | 		 ")
print ("|__|__||__|\_||____||__|__||__|__||__|\_||____|		 ")	                                              
print ("=====================================================")
print ("Angka Biner diawali dengan 0b, hexadecimal diawali 0x")
print ("=====================================================")
print ("1. Desimal")
print ("2. Biner")
print ("3. Hexadecimal")
print ("=====================")

i = int(input("Masukkan pilihan anda: "))
if i == 1:
    x = int(input("Masukkan angka Desimal: "))
    print ('Desimal ='),(x)
    print ('Biner ='),(bin(x))
    print ('hexadecimal ='),(hex(x))
if i == 2:
	x = int(input("Masukkan angka biner: "))
	print ('Desimal ='),(x)
	print ('Biner ='),(bin(x))
	print ('hexadecimal ='),(hex(x))
if i == 3:
	x = int(input("Masukkan angka hexadecimal: "))
	print ('Desimal ='),(x)
	print ('Biner ='),(bin(x))
	print ('hexadecimal ='),(hex(x))